---
- name: Load all hosts for availability
  hosts: all
  tasks:
  - name: debug
    debug:
      msg: "All"
- name: Main.yml @common
  hosts: vault
  become: yes
  roles:
    # - common
    # - { role: consul, consul_type: 'client' }
    - vault
